export const SET_VIDEO_ROWS = "SET_VIDEO_ROWS";
export const SET_MIC_ON = "SET_MIC_ON";
export const SET_VIDEO_ON = "SET_VIDEO_ON";
export const SET_SCREEN_SHARING_STATUS = "SET_SCREEN_SHARING_STATUS";
export const SET_CC_ON = "SET_CC_ON";
export const SET_LOCAL_USER_STREAM = "SET_LOCAL_USER_STREAM";
export const SET_USER_DISPLAY_NAME = "SET_USER_DISPLAY_NAME";
export const SET_LOCAL_USER_PEER = "SET_LOCAL_USER_PEER";
