export const SET_VIDEO_ROWS = "SET_VIDEO_ROWS";
export const SET_MIC_ON = "SET_MIC_ON";
export const SET_VIDEO_ON = "SET_VIDEO_ON";
export const SET_SCREEN_SHARING_STATUS = "SET_SCREEN_SHARING_STATUS";
export const SET_CC_ON = "SET_CC_ON";
export const SET_LOCAL_USER_STREAM = "SET_LOCAL_USER_STREAM";
export const SET_USER_DISPLAY_NAME = "SET_USER_DISPLAY_NAME";
export const SET_LOCAL_USER_PEER = "SET_LOCAL_USER_PEER";
export const SETL_LOCAL_USER_ID = "SETL_LOCAL_USER_ID";
export const SET_LOCAL_USER_SCREEN_SHARING_PEER =
  "SET_LOCAL_USER_SCREEN_SHARING_PEER";
export const SET_LOCAL_USER_SCREEN_SHARING_ID =
  "SET_LOCAL_USER_SCREEN_SHARING_ID";
export const SET_CONNECTIONS = "SET_CONNECTIONS";
export const SET_REMOTE_CONNECTIONS_ID = "SET_REMOTE_CONNECTIONS_ID";
export const SET_LOCAL_USER_SCREEN_SHARING_STREAM =
  "SET_LOCAL_USER_SCREEN_SHARING_STREAM";
