export const SET_VIDEO_ROWS = "SET_VIDEO_ROWS";
export const SET_MIC_ON = "SET_MIC_ON";
export const SET_VIDEO_ON = "SET_VIDEO_ON";
export const SET_SCREEN_SHARING_STATUS = "SET_SCREEN_SHARING_STATUS";
